language: elixir

elixir:
  - 1.8.0

otp_release:
  - 21.2

services:
  - postgresql

before_script:
  - MIX_ENV=test mix do event_store.create, event_store.init

sudo: required
dist: trusty

addons:
  postgresql: "9.6"
